// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product_name_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ProductNameResponseImpl _$$ProductNameResponseImplFromJson(
  Map<String, dynamic> json,
) => _$ProductNameResponseImpl(
  productId: (json['product_id'] as num?)?.toInt(),
  productCode: json['product_code'] as String?,
  productName: json['product_name'] as String?,
  productPrice: (json['product_price'] as num?)?.toDouble(),
  oldProductPrice: json['old_product_price'] as String?,
  prodVarId: (json['prod_var_id'] as num?)?.toInt(),
  prodVarCode: parseInt(json['prod_var_code']),
  productDesc: json['product_desc'] as String?,
  productArabicDesc: json['product_arabic_desc'] as String?,
  productArabicName: json['product_arabic_name'] as String?,
  storeId: (json['store_id'] as num?)?.toInt(),
  purchasePrice: (json['purchase_price'] as num?)?.toInt(),
  offerPrice: (json['offer_price'] as num?)?.toInt(),
  productQty: (json['product_qty'] as num?)?.toInt(),
  productFeatured: (json['product_featured'] as num?)?.toInt(),
  maintainStock: (json['maintain_stock'] as num?)?.toInt(),
  isOutOfStock: (json['is_out_of_stock'] as num?)?.toInt(),
  prodMenuOrder: (json['prod_menu_order'] as num?)?.toInt(),
  variants: json['variants'] as List<dynamic>?,
  isHidden: (json['is_hidden'] as num?)?.toInt(),
  hideRemarks: json['hide_remarks'] as String?,
  hasReview: (json['has_review'] as num?)?.toInt(),
  editMode: (json['edit_mode'] as num?)?.toInt(),
  isVariant: (json['is_variant'] as num?)?.toInt(),
  productPriceRange: json['product_price_range'],
  showPrice: (json['show_price'] as num?)?.toInt(),
  showProductRange: (json['show_product_range'] as num?)?.toInt(),
  storeListing: (json['store_listing'] as num?)?.toInt(),
  currencyCode: json['currency_code'] as String?,
  storeProductId: (json['store_product_id'] as num?)?.toInt(),
  stockIntervalId: (json['stock_interval_id'] as num?)?.toInt(),
  rawcount: (json['rawcount'] as num?)?.toInt(),
  varRowCount: (json['var_row_count'] as num?)?.toInt(),
  takeawayAddonPrice: (json['takeaway_addon_price'] as num?)?.toInt(),
  deliveryAddonPrice: (json['delivery_addon_price'] as num?)?.toInt(),
  webProductPrice: json['web_product_price'],
  appProductPrice: json['app_product_price'],
  posProductPrice: json['pos_product_price'],
  wholesaleProductPrice: (json['wholesale_product_price'] as num?)?.toDouble(),
  retailProductPrice: (json['retail_product_price'] as num?)?.toDouble(),
  categoryName: json['category_name'] as String?,
  stockInterval: json['stock_interval'] as String?,
  hour: json['hour'] as String?,
  unitId: (json['unit_id'] as num?)?.toInt(),
  unitName: json['unit_name'] as String?,
  images: (json['images'] as List<dynamic>?)
      ?.map((e) => Image.fromJson(e as Map<String, dynamic>))
      .toList(),
  isPriceEditable: (json['is_price_editable'] as num?)?.toInt(),
);

Map<String, dynamic> _$$ProductNameResponseImplToJson(
  _$ProductNameResponseImpl instance,
) => <String, dynamic>{
  'product_id': instance.productId,
  'product_code': instance.productCode,
  'product_name': instance.productName,
  'product_price': instance.productPrice,
  'old_product_price': instance.oldProductPrice,
  'prod_var_id': instance.prodVarId,
  'prod_var_code': instance.prodVarCode,
  'product_desc': instance.productDesc,
  'product_arabic_desc': instance.productArabicDesc,
  'product_arabic_name': instance.productArabicName,
  'store_id': instance.storeId,
  'purchase_price': instance.purchasePrice,
  'offer_price': instance.offerPrice,
  'product_qty': instance.productQty,
  'product_featured': instance.productFeatured,
  'maintain_stock': instance.maintainStock,
  'is_out_of_stock': instance.isOutOfStock,
  'prod_menu_order': instance.prodMenuOrder,
  'variants': instance.variants,
  'is_hidden': instance.isHidden,
  'hide_remarks': instance.hideRemarks,
  'has_review': instance.hasReview,
  'edit_mode': instance.editMode,
  'is_variant': instance.isVariant,
  'product_price_range': instance.productPriceRange,
  'show_price': instance.showPrice,
  'show_product_range': instance.showProductRange,
  'store_listing': instance.storeListing,
  'currency_code': instance.currencyCode,
  'store_product_id': instance.storeProductId,
  'stock_interval_id': instance.stockIntervalId,
  'rawcount': instance.rawcount,
  'var_row_count': instance.varRowCount,
  'takeaway_addon_price': instance.takeawayAddonPrice,
  'delivery_addon_price': instance.deliveryAddonPrice,
  'web_product_price': instance.webProductPrice,
  'app_product_price': instance.appProductPrice,
  'pos_product_price': instance.posProductPrice,
  'wholesale_product_price': instance.wholesaleProductPrice,
  'retail_product_price': instance.retailProductPrice,
  'category_name': instance.categoryName,
  'stock_interval': instance.stockInterval,
  'hour': instance.hour,
  'unit_id': instance.unitId,
  'unit_name': instance.unitName,
  'images': instance.images,
  'is_price_editable': instance.isPriceEditable,
};

_$ImageImpl _$$ImageImplFromJson(Map<String, dynamic> json) => _$ImageImpl(
  productImgId: (json['product_img_id'] as num?)?.toInt(),
  resourceId: (json['resource_id'] as num?)?.toInt(),
  prodVarId: (json['prod_var_id'] as num?)?.toInt(),
  large: json['Large'] as String?,
  medium: json['Medium'] as String?,
  small: json['Small'] as String?,
);

Map<String, dynamic> _$$ImageImplToJson(_$ImageImpl instance) =>
    <String, dynamic>{
      'product_img_id': instance.productImgId,
      'resource_id': instance.resourceId,
      'prod_var_id': instance.prodVarId,
      'Large': instance.large,
      'Medium': instance.medium,
      'Small': instance.small,
    };
