// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'create_product_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$CreateProductResponseImpl _$$CreateProductResponseImplFromJson(
  Map<String, dynamic> json,
) => _$CreateProductResponseImpl(
  productId: (json['product_id'] as num?)?.toInt(),
  storeId: (json['store_id'] as num?)?.toInt(),
  mainCategoryId: (json['main_category_id'] as num?)?.toInt(),
  productCategories: json['Product_categories'] as List<dynamic>?,
  brandId: (json['brand_id'] as num?)?.toInt(),
  unitId: (json['unit_id'] as num?)?.toInt(),
  prodTypeId: (json['prod_type_id'] as num?)?.toInt(),
  productCode: json['product_code'] as String?,
  productSlug: json['product_slug'] as String?,
  productName: json['product_name'] as String?,
  services: (json['services'] as List<dynamic>?)
      ?.map((e) => (e as num).toInt())
      .toList(),
  productImages: (json['product_images'] as List<dynamic>?)
      ?.map((e) => Image.fromJson(e as Map<String, dynamic>))
      .toList(),
  productArabicName: json['product_arabic_name'] as String?,
  productShortName: json['product_short_name'] as String?,
  itemsPerPack: json['items_per_pack'],
  minOrderQty: json['min_order_qty'],
  productDesc: json['product_desc'] as String?,
  productArabicDesc: json['product_arabic_desc'],
  volume: json['volume'],
  productPrice: (json['product_price'] as num?)?.toInt(),
  purchasePrice: (json['purchase_price'] as num?)?.toInt(),
  takeawayAddonPrice: (json['takeaway_addon_price'] as num?)?.toInt(),
  deliveryAddonPrice: (json['delivery_addon_price'] as num?)?.toInt(),
  webProductPrice: (json['web_product_price'] as num?)?.toInt(),
  appProductPrice: (json['app_product_price'] as num?)?.toInt(),
  posProductPrice: (json['pos_product_price'] as num?)?.toInt(),
  wholesaleProductPrice: (json['wholesale_product_price'] as num?)?.toInt(),
  retailProductPrice: (json['retail_product_price'] as num?)?.toInt(),
  isOfferProduct: (json['is_offer_product'] as num?)?.toInt(),
  isTaxable: (json['is_taxable'] as num?)?.toInt(),
  isTaxInclusive: (json['is_tax_inclusive'] as num?)?.toInt(),
  productTaxAmt: json['product_tax_amt'],
  productTaxPercentage: json['product_tax_percentage'],
  productSku: json['product_sku'] as String?,
  productFeatured: (json['product_featured'] as num?)?.toInt(),
  productShortDescription: json['product_short_description'] as String?,
  isHidden: (json['is_hidden'] as num?)?.toInt(),
  productSeoUrl: json['product_seo_url'],
  isVariant: (json['is_variant'] as num?)?.toInt(),
  prodPurchaseLimit: json['prod_purchase_limit'],
  prodShipCharge: json['prod_ship_charge'],
  prodSeoKeyword: json['prod_seo_keyword'],
  isGuarantee: (json['is_guarantee'] as num?)?.toInt(),
  prodSeoTitle: json['prod_seo_title'],
  prodSeoDesc: json['prod_seo_desc'],
  prodVideoLink: json['prod_video_link'],
  prodTwiterLink: json['prod_twiter_link'],
  prodWarrantyDesc: json['prod_warranty_desc'],
  stockIntervalId: (json['stock_interval_id'] as num?)?.toInt(),
  prodMenuOrder: (json['prod_menu_order'] as num?)?.toInt(),
  isBestSeller: (json['is_best_seller'] as num?)?.toInt(),
  ignoreDiscount: (json['ignore_discount'] as num?)?.toInt(),
  prodWeight: json['prod_weight'],
  hasService: (json['has_service'] as num?)?.toInt(),
  prodLength: json['prod_length'],
  prodHeight: json['prod_height'],
  prodWidth: json['prod_width'],
  reorderQty: json['reorder_qty'],
  createdBy: (json['created_by'] as num?)?.toInt(),
  updatedBy: (json['updated_by'] as num?)?.toInt(),
  isOutOfStock: (json['is_out_of_stock'] as num?)?.toInt(),
  isCombo: (json['is_combo'] as num?)?.toInt(),
  isShopOnly: (json['is_shop_only'] as num?)?.toInt(),
  isNew: (json['is_new'] as num?)?.toInt(),
  productPriceRange: json['product_price_range'],
  showPrice: json['show_price'],
  showProductRange: json['show_product_range'],
  isActive: (json['is_active'] as num?)?.toInt(),
  hasReview: json['has_review'],
  shelfNo: json['shelf_no'],
  hideRemarks: json['hide_remarks'],
  returnablePeriod: (json['returnable_period'] as num?)?.toInt(),
  isPreOrder: (json['is_pre_order'] as num?)?.toInt(),
  releaseTime: json['release_time'],
  preOrderFee: json['pre_order_fee'],
  preOrderChargingOptionId: (json['pre_order_charging_option_id'] as num?)
      ?.toInt(),
  isSellable: (json['is_sellable'] as num?)?.toInt(),
  isPurchasable: (json['is_purchasable'] as num?)?.toInt(),
  productBarcode: json['product_barcode'] as String?,
  isPriceEditable: (json['is_price_editable'] as num?)?.toInt(),
  prodAmazonLink: json['prod_amazon_link'],
  prodFlipkartLink: json['prod_flipkart_link'],
  isFastMoving: (json['is_fast_moving'] as num?)?.toInt(),
  expiryDays: (json['expiry_days'] as num?)?.toInt(),
  quantityPerUnit: (json['quantity_per_unit'] as num?)?.toInt(),
  separateVariantStock: json['separate_variant_stock'],
  updatedAt: json['updated_at'] == null
      ? null
      : DateTime.parse(json['updated_at'] as String),
  createdAt: json['created_at'] == null
      ? null
      : DateTime.parse(json['created_at'] as String),
);

Map<String, dynamic> _$$CreateProductResponseImplToJson(
  _$CreateProductResponseImpl instance,
) => <String, dynamic>{
  'product_id': instance.productId,
  'store_id': instance.storeId,
  'main_category_id': instance.mainCategoryId,
  'Product_categories': instance.productCategories,
  'brand_id': instance.brandId,
  'unit_id': instance.unitId,
  'prod_type_id': instance.prodTypeId,
  'product_code': instance.productCode,
  'product_slug': instance.productSlug,
  'product_name': instance.productName,
  'services': instance.services,
  'product_images': instance.productImages,
  'product_arabic_name': instance.productArabicName,
  'product_short_name': instance.productShortName,
  'items_per_pack': instance.itemsPerPack,
  'min_order_qty': instance.minOrderQty,
  'product_desc': instance.productDesc,
  'product_arabic_desc': instance.productArabicDesc,
  'volume': instance.volume,
  'product_price': instance.productPrice,
  'purchase_price': instance.purchasePrice,
  'takeaway_addon_price': instance.takeawayAddonPrice,
  'delivery_addon_price': instance.deliveryAddonPrice,
  'web_product_price': instance.webProductPrice,
  'app_product_price': instance.appProductPrice,
  'pos_product_price': instance.posProductPrice,
  'wholesale_product_price': instance.wholesaleProductPrice,
  'retail_product_price': instance.retailProductPrice,
  'is_offer_product': instance.isOfferProduct,
  'is_taxable': instance.isTaxable,
  'is_tax_inclusive': instance.isTaxInclusive,
  'product_tax_amt': instance.productTaxAmt,
  'product_tax_percentage': instance.productTaxPercentage,
  'product_sku': instance.productSku,
  'product_featured': instance.productFeatured,
  'product_short_description': instance.productShortDescription,
  'is_hidden': instance.isHidden,
  'product_seo_url': instance.productSeoUrl,
  'is_variant': instance.isVariant,
  'prod_purchase_limit': instance.prodPurchaseLimit,
  'prod_ship_charge': instance.prodShipCharge,
  'prod_seo_keyword': instance.prodSeoKeyword,
  'is_guarantee': instance.isGuarantee,
  'prod_seo_title': instance.prodSeoTitle,
  'prod_seo_desc': instance.prodSeoDesc,
  'prod_video_link': instance.prodVideoLink,
  'prod_twiter_link': instance.prodTwiterLink,
  'prod_warranty_desc': instance.prodWarrantyDesc,
  'stock_interval_id': instance.stockIntervalId,
  'prod_menu_order': instance.prodMenuOrder,
  'is_best_seller': instance.isBestSeller,
  'ignore_discount': instance.ignoreDiscount,
  'prod_weight': instance.prodWeight,
  'has_service': instance.hasService,
  'prod_length': instance.prodLength,
  'prod_height': instance.prodHeight,
  'prod_width': instance.prodWidth,
  'reorder_qty': instance.reorderQty,
  'created_by': instance.createdBy,
  'updated_by': instance.updatedBy,
  'is_out_of_stock': instance.isOutOfStock,
  'is_combo': instance.isCombo,
  'is_shop_only': instance.isShopOnly,
  'is_new': instance.isNew,
  'product_price_range': instance.productPriceRange,
  'show_price': instance.showPrice,
  'show_product_range': instance.showProductRange,
  'is_active': instance.isActive,
  'has_review': instance.hasReview,
  'shelf_no': instance.shelfNo,
  'hide_remarks': instance.hideRemarks,
  'returnable_period': instance.returnablePeriod,
  'is_pre_order': instance.isPreOrder,
  'release_time': instance.releaseTime,
  'pre_order_fee': instance.preOrderFee,
  'pre_order_charging_option_id': instance.preOrderChargingOptionId,
  'is_sellable': instance.isSellable,
  'is_purchasable': instance.isPurchasable,
  'product_barcode': instance.productBarcode,
  'is_price_editable': instance.isPriceEditable,
  'prod_amazon_link': instance.prodAmazonLink,
  'prod_flipkart_link': instance.prodFlipkartLink,
  'is_fast_moving': instance.isFastMoving,
  'expiry_days': instance.expiryDays,
  'quantity_per_unit': instance.quantityPerUnit,
  'separate_variant_stock': instance.separateVariantStock,
  'updated_at': instance.updatedAt?.toIso8601String(),
  'created_at': instance.createdAt?.toIso8601String(),
};

_$ImageImpl _$$ImageImplFromJson(Map<String, dynamic> json) => _$ImageImpl(
  productImgId: (json['product_img_id'] as num?)?.toInt(),
  resourceId: (json['resource_id'] as num?)?.toInt(),
  prodVarId: (json['prod_var_id'] as num?)?.toInt(),
  large: json['Large'] as String?,
  medium: json['Medium'] as String?,
  small: json['Small'] as String?,
);

Map<String, dynamic> _$$ImageImplToJson(_$ImageImpl instance) =>
    <String, dynamic>{
      'product_img_id': instance.productImgId,
      'resource_id': instance.resourceId,
      'prod_var_id': instance.prodVarId,
      'Large': instance.large,
      'Medium': instance.medium,
      'Small': instance.small,
    };
