// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'order_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$OrderResponseImpl _$$OrderResponseImplFromJson(Map<String, dynamic> json) =>
    _$OrderResponseImpl(
      prodOrderId: (json['prod_order_id'] as num?)?.toInt(),
      orderStatusId: (json['order_status_id'] as num?)?.toInt(),
      orderGroupId: json['order_group_id'] as String?,
      isCkdForEdit: (json['is_ckd_for_edit'] as num?)?.toInt(),
      referenceTypeId: json['reference_type_id'],
      billNo: json['bill_no'] as String?,
      billCustName: json['bill_cust_name'] as String?,
      billFlatNo: json['bill_flat_no'] as String?,
      billBuildingNo: json['bill_building_no'] as String?,
      billDoorNo: json['bill_door_no'] as String?,
      billCity: json['bill_city'] as String?,
      billMobile: json['bill_mobile'] as String?,
      orderDate: json['order_date'] as String?,
      orderOptionId: (json['order_option_id'] as num?)?.toInt(),
      paymentMethodId: (json['payment_method_id'] as num?)?.toInt(),
      paymentStatusId: (json['payment_status_id'] as num?)?.toInt(),
      notificationStatusId: (json['notification_status_id'] as num?)?.toInt(),
      notificationStatusName: json['notification_status_name'] as String?,
      deliveryDate: json['delivery_date'] as String?,
      netAmount: (json['net_amount'] as num?)?.toDouble(),
      orderDiscAmount: (json['order_disc_amount'] as num?)?.toInt(),
      storeId: (json['store_id'] as num?)?.toInt(),
      dayCloseId: (json['day_close_id'] as num?)?.toInt(),
      custId: (json['cust_id'] as num?)?.toInt(),
      orderStatusName: json['order_status_name'] as String?,
      payMethodName: json['pay_method_name'] as String?,
      paymentStatusName: json['payment_status_name'] as String?,
      orderOptionName: json['order_option_name'] as String?,
      deliveryBoyId: json['delivery_boy_id'] as String?,
      deliveryBoyName: json['delivery_boy_name'] as String?,
      isDeliveryAssigned: (json['is_delivery_assigned'] as num?)?.toInt(),
      deliveryPartnerId: (json['delivery_partner_id'] as num?)?.toInt(),
      delPartnerName: json['del_partner_name'] as String?,
      rowcount: (json['rowcount'] as num?)?.toInt(),
      totalNetAmount: parseNumberAsDouble(json['total_net_amount']),
      orderGroupTotal: parseNumberAsDouble(json['order_group_total']),
      orderGroupCount: parseNumberAsDouble(json['order_group_count']),
      delAssignType: parseNumberAsDouble(json['del_assign_type']),
    );

Map<String, dynamic> _$$OrderResponseImplToJson(_$OrderResponseImpl instance) =>
    <String, dynamic>{
      'prod_order_id': instance.prodOrderId,
      'order_status_id': instance.orderStatusId,
      'order_group_id': instance.orderGroupId,
      'is_ckd_for_edit': instance.isCkdForEdit,
      'reference_type_id': instance.referenceTypeId,
      'bill_no': instance.billNo,
      'bill_cust_name': instance.billCustName,
      'bill_flat_no': instance.billFlatNo,
      'bill_building_no': instance.billBuildingNo,
      'bill_door_no': instance.billDoorNo,
      'bill_city': instance.billCity,
      'bill_mobile': instance.billMobile,
      'order_date': instance.orderDate,
      'order_option_id': instance.orderOptionId,
      'payment_method_id': instance.paymentMethodId,
      'payment_status_id': instance.paymentStatusId,
      'notification_status_id': instance.notificationStatusId,
      'notification_status_name': instance.notificationStatusName,
      'delivery_date': instance.deliveryDate,
      'net_amount': instance.netAmount,
      'order_disc_amount': instance.orderDiscAmount,
      'store_id': instance.storeId,
      'day_close_id': instance.dayCloseId,
      'cust_id': instance.custId,
      'order_status_name': instance.orderStatusName,
      'pay_method_name': instance.payMethodName,
      'payment_status_name': instance.paymentStatusName,
      'order_option_name': instance.orderOptionName,
      'delivery_boy_id': instance.deliveryBoyId,
      'delivery_boy_name': instance.deliveryBoyName,
      'is_delivery_assigned': instance.isDeliveryAssigned,
      'delivery_partner_id': instance.deliveryPartnerId,
      'del_partner_name': instance.delPartnerName,
      'rowcount': instance.rowcount,
      'total_net_amount': instance.totalNetAmount,
      'order_group_total': instance.orderGroupTotal,
      'order_group_count': instance.orderGroupCount,
      'del_assign_type': instance.delAssignType,
    };
