import 'package:freezed_annotation/freezed_annotation.dart';

part 'company_response.freezed.dart';
part 'company_response.g.dart';

@freezed
class CompanyResponse with _$CompanyResponse {
  const factory CompanyResponse({
    @JsonKey(name: "company_id") int? companyId,
    // @JsonKey(name: "android_ver") String? androidVer,
    // @JsonKey(name: "android_ver_critical") int? androidVerCritical,
    // @JsonKey(name: "ios_ver") String? iosVer,
    // @JsonKey(name: "ios_ver_critical") int? iosVerCritical,
    // @JsonKey(name: "comp_light_logo") dynamic compLightLogo,
    // @JsonKey(name: "comp_name") String? compName,
    // @JsonKey(name: "comp_address") String? compAddress,
    // @JsonKey(name: "comp_email") String? compEmail,
    // @JsonKey(name: "comp_phone") int? compPhone,
    // @JsonKey(name: "comp_website") String? compWebsite,
    // @JsonKey(name: "comp_certifi") String? compCertifi,
    // @JsonKey(name: "country_id") int? countryId,
    // @JsonKey(name: "state_id") int? stateId,
    // @JsonKey(name: "currency_id") int? currencyId,
    // @JsonKey(name: "language_id") int? languageId,
    // @JsonKey(name: "about_us") String? aboutUs,
    // @JsonKey(name: "about_us_arabic") dynamic aboutUsArabic,
    // @JsonKey(name: "latitude") String? latitude,
    // @JsonKey(name: "longitude") String? longitude,
   @JsonKey(name: "cdn_url") String? cdnUrl,
    // @JsonKey(name: "fb_url") String? fbUrl,
    // @JsonKey(name: "twitter_url") String? twitterUrl,
    // @JsonKey(name: "youtube_url") String? youtubeUrl,
    // @JsonKey(name: "instagram_url") String? instagramUrl,
    // @JsonKey(name: "is_active") int? isActive,
    // @JsonKey(name: "created_by") int? createdBy,
    // @JsonKey(name: "updated_by") int? updatedBy,
    // @JsonKey(name: "created_at") dynamic createdAt,
    // @JsonKey(name: "updated_at") DateTime? updatedAt,
    // @JsonKey(name: "authentication_type_id") int? authenticationTypeId,
    // @JsonKey(name: "mobile_logo") int? mobileLogo,
    // @JsonKey(name: "admin_url") dynamic adminUrl,
    // @JsonKey(name: "return_policy") dynamic returnPolicy,
    // @JsonKey(name: "return_policy_arabic") dynamic returnPolicyArabic,
    // @JsonKey(name: "term_of_use") String? termOfUse,
    // @JsonKey(name: "term_of_use_arabic") dynamic termOfUseArabic,
    // @JsonKey(name: "warranty_policy") dynamic warrantyPolicy,
    // @JsonKey(name: "warranty_policy_arabic") dynamic warrantyPolicyArabic,
    // @JsonKey(name: "privacy_policy") dynamic privacyPolicy,
    // @JsonKey(name: "privacy_policy_arabic") dynamic privacyPolicyArabic,
    // @JsonKey(name: "resource_id") int? resourceId,
    // @JsonKey(name: "favicon") int? favicon,
    // @JsonKey(name: "is_maintenance") int? isMaintenance,
    // @JsonKey(name: "android_adm_ver") String? androidAdmVer,
    // @JsonKey(name: "android_adm_ver_critical") int? androidAdmVerCritical,
    // @JsonKey(name: "ios_adm_ver") dynamic iosAdmVer,
    // @JsonKey(name: "ios_adm_ver_critical") dynamic iosAdmVerCritical,
    // @JsonKey(name: "android_del_ver") dynamic androidDelVer,
    // @JsonKey(name: "ios_del_ver") dynamic iosDelVer,
    // @JsonKey(name: "android_del_ver_critical") dynamic androidDelVerCritical,
    // @JsonKey(name: "ios_del_ver_critical") dynamic iosDelVerCritical,
    // @JsonKey(name: "del_charge_type") int? delChargeType,
    // @JsonKey(name: "working_version_limit_android")
    // double? workingVersionLimitAndroid,
    // @JsonKey(name: "working_version_limit_ios") double? workingVersionLimitIos,
    // @JsonKey(name: "tenant_id") int? tenantId,
    // @JsonKey(name: "working_adm_version_limit_android")
    // dynamic workingAdmVersionLimitAndroid,
    // @JsonKey(name: "working_del_version_limit_android")
    // dynamic workingDelVersionLimitAndroid,
    // @JsonKey(name: "working_adm_version_limit_ios")
    // dynamic workingAdmVersionLimitIos,
    // @JsonKey(name: "working_del_version_limit_ios")
    // dynamic workingDelVersionLimitIos,
    // @JsonKey(name: "store_filter_distance") int? storeFilterDistance,
    // @JsonKey(name: "is_global_inventory") int? isGlobalInventory,
    // @JsonKey(name: "customer_splash") dynamic companyResponseCustomerSplash,
    // @JsonKey(name: "delivery_module") dynamic deliveryModule,
    // @JsonKey(name: "admin_splash") dynamic companyResponseAdminSplash,
    // @JsonKey(name: "og_title") String? ogTitle,
    // @JsonKey(name: "og_description") String? ogDescription,
    // @JsonKey(name: "description") String? description,
    // @JsonKey(name: "site_key") String? siteKey,
    // @JsonKey(name: "secret_key") String? secretKey,
    // @JsonKey(name: "keywords") String? keywords,
    // @JsonKey(name: "og_image") int? companyResponseOgImage,
    // @JsonKey(name: "map") dynamic map,
    // @JsonKey(name: "is_google_capture") int? isGoogleCapture,
    // @JsonKey(name: "app_package_id") dynamic appPackageId,
    // @JsonKey(name: "ios_app_id") dynamic iosAppId,
    // @JsonKey(name: "adm_android_pack_id") dynamic admAndroidPackId,
    // @JsonKey(name: "adm_ios_pack_id") dynamic admIosPackId,
    // @JsonKey(name: "del_app_andriod_pack_id") dynamic delAppAndriodPackId,
    // @JsonKey(name: "del_app_ios_pack_id") dynamic delAppIosPackId,
    // @JsonKey(name: "robots_content") String? robotsContent,
    // @JsonKey(name: "google_tag_manager_script") String? googleTagManagerScript,
    // @JsonKey(name: "is_mvm") int? isMvm,
    // @JsonKey(name: "meta_description") dynamic metaDescription,
    // @JsonKey(name: "qr_menu_url") dynamic qrMenuUrl,
    // @JsonKey(name: "storage_type") int? storageType,
    // @JsonKey(name: "upload_path") String? uploadPath,
    // @JsonKey(name: "global_company_id") String? globalCompanyId,
    // @JsonKey(name: "delivery_agent_max_distance")
    // double? deliveryAgentMaxDistance,
    // @JsonKey(name: "primary_login_method") int? primaryLoginMethod,
    // @JsonKey(name: "production") int? production,
    // @JsonKey(name: "currency_name") String? currencyName,
    // @JsonKey(name: "decimal_digits") dynamic decimalDigits,
    // @JsonKey(name: "decimal_rounding_id") dynamic decimalRoundingId,
    // @JsonKey(name: "currency_code") String? currencyCode,
    // @JsonKey(name: "currency_arabic") dynamic currencyArabic,
    // @JsonKey(name: "mobile_digit") int? mobileDigit,
    // @JsonKey(name: "validation_msg") dynamic validationMsg,
    // @JsonKey(name: "state_name") String? stateName,
    // @JsonKey(name: "country_name") String? countryName,
    // @JsonKey(name: "country_isd") String? countryIsd,
    // @JsonKey(name: "language_name") String? languageName,
    // @JsonKey(name: "user_name") dynamic userName,
    // @JsonKey(name: "authentication_type_name") String? authenticationTypeName,
    // @JsonKey(name: "tenant_name") String? tenantName,
    // @JsonKey(name: "Large") String? large,
    // @JsonKey(name: "Medium") String? medium,
    // @JsonKey(name: "Small") String? small,
    // @JsonKey(name: "MobileLarge") dynamic mobileLarge,
    // @JsonKey(name: "MobileMedium") dynamic mobileMedium,
    // @JsonKey(name: "MobileSmall") dynamic mobileSmall,
    // @JsonKey(name: "FavICON") dynamic favIcon,
    @JsonKey(name: "LargeLightLogo") dynamic largeLightLogo,
    @JsonKey(name: "MediumLightLogo") dynamic mediumLightLogo,
    @JsonKey(name: "SmallLightLogo") dynamic smallLightLogo,
    @JsonKey(name: "CustomerSplash") dynamic customerSplash,
    @JsonKey(name: "AdminSplash") dynamic adminSplash,
    @JsonKey(name: "DeliverySplash") dynamic deliverySplash,
    @JsonKey(name: "OgImage") dynamic ogImage,
    @JsonKey(name: "contact_us_url") String? contactUsUrl,
    @JsonKey(name: "driver_reg_url") String? driverRegUrl,
    @JsonKey(name: "seller_reg_url") String? sellerRegUrl,
    @JsonKey(name: "default_store_id") int? defaultStoreId,
    @JsonKey(name: "sms_gateway_enabled") int? smsGatewayEnabled,
  }) = _CompanyResponse;

  factory CompanyResponse.fromJson(Map<String, dynamic> json) =>
      _$CompanyResponseFromJson(json);
}
